version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: api-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '@thermaspg@'
      POSTGRES_DB: 'api-cm'
    ports:
      - '5432:5432'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - network-api-cm

  app:
    container_name: api-cmnet
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run dev
    ports:
      - '3333:3333'
    volumes:
      - './:/usr/app'
    depends_on:
      - postgres
    networks:
      - network-api-cm

networks:
  network-api-cm:
    driver: bridge

