version: '3'

services:
  app:
    container_name: web-cmnet-integration
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/app'
    networks:
      - network-api-cm

networks:
  network-api-cm:
    driver: bridge

