version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: '@thermas@'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /home/mabu/Docker/postgresql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - network-api-cm

  server:
    container_name: api-cmnet-integration
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    volumes:
      - './:/usr/app'
      - '/home/mabu/cmnet/server/data:/usr/app/data'
      - /etc/localtime:/etc/localtime:ro
    networks:
      - network-api-cm

networks:
  network-api-cm:
    driver: bridge

