version: '3'

services:
  app:
    container_name: api-cmnet-integration
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run dev
    ports:
      - '3333:3333'
    volumes:
      - './:/usr/app'
    networks:
      - network-api-cm

networks:
  network-api-cm:
    driver: bridge

